### ISSUE TITLE
App throws an error when adding Expense

### ISSUE THREAD

**Issue by Abhimanyu-Jana** [Abhimanyu-Jana/Xpenza#1]
<pre>
W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.xpenza.XpenzaDBHelper.insertExpense(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)' on a null object reference
W/System.err:     at com.xpenza.MainActivity.addOrViewData(MainActivity.java:113)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288)
W/System.err:     at android.view.View.performClick(View.java:5637)
W/System.err:     at android.view.View$PerformClick.run(View.java:22429)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:751)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err:     at android.os.Looper.loop(Looper.java:154)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6119)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.xpenza.XpenzaDBHelper.insertExpense(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)' on a null object reference
W/System.err:     at com.xpenza.MainActivity.addOrViewData(MainActivity.java:113)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288)
W/System.err:     at android.view.View.performClick(View.java:5637)
W/System.err:     at android.view.View$PerformClick.run(View.java:22429)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:751)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err:     at android.os.Looper.loop(Looper.java:154)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6119)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
</pre>

**Comment by Abhimanyu-Jana** [comment]
Fixed
